//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_App.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers_to_the_Questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Answers_to_the_Questions()
        {
            this.Answering_the_Question = new HashSet<Answering_the_Question>();
        }
    
        public int id { get; set; }
        public int question_id { get; set; }
        public string text { get; set; }
        public int type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answering_the_Question> Answering_the_Question { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
